service: gettogether

provider:
    name: aws
    runtime: nodejs12.x
    region: eu-west-1
    stage: dev2

functions:
    helloWorld:
        handler: src/functions/helloWorld.handler
        events:
            - http:
                path: api/helloWorld/{name}
                method: get
